### PR TITLE
Add nvme binary

### PR DESCRIPTION
**Pull request by yacoob**
...so telegraf can grab SMART data off nvme drives.

# Fix or Feature Request?
<!--- Is this pull request to fix something or is a feature request ---!>
<!--- If this is a fix has a issue been raised? (anything other than a typo) ---!>

# What does this solve

https://github.com/sabuto/hassio-repo/issues/13

### CODE REVIEW

**Comment by sabuto** [comment]
Did you test this?

**Comment by yacoob** [comment]
nope - didn't have a test instance of HA to test it up, sorry :|

**Comment by sabuto** [comment]
No worries I will dowoad and test this locally next week

**Comment by yacoob** [comment]
Any luck so far? :)

**Pull request closed without merging**
